
- name: Add Nginx Repo
  yum:
    name: epel-release
    state: latest

- name: Install Nginx
  yum:
    name: nginx
    state: latest

# Allows https traffic (firewall-cmd --permanent --zone=public --add-service=http(s))
- name: Allow HTTP traffic through firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    zone: public
    state: enabled
  with_items:
    - http
    - https
  notify: reload firewalld
    
# Remove nginx.conf
 - name: Removing default nginx.conf
   file:
     path: /etc/nginx/nginx.conf
     state: absent
    
 # Copy nginx.conf template
 - name: Copying nginx.conf template
   template:
     src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf
     owner: root
     group: root
     mode: 0644
   notify: restart nginx